### ISSUE TITLE
User can edit previously entered tasks

### ISSUE THREAD

**Issue by yl-coder** [cs2103aug2015-f09-3j/main#4]
So that user can quickly amend mistake made on the previously entered task.

**Comment by nghuiyirebecca** [comment]
User keys in the word "edit -----" with the parameters at the back. Once the task is found, we lsit the parameters that we can edit. the user will key in the number that corresponds to the parameter they want to edit and change it. must change the type of task as well. 
1. Event
2. Location
3. Date 
4. Time

1 meeting
